# kubectl apply -f saori-apaza-01-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: saori-apaza-01-secret
  namespace: saori-apaza-01-namespace
type: Opaque
data:
  DATABASE_NAME: V2luZXM=   # en Base64
  DATABASE_URI: bW9uZ29kYitzcnY6Ly9zYW9yaWFwYXphYWxkYXphYmFsX2RiX3VzZXI6enRENXhUREg1RW9hVGs4QUBjbHVzdGVyMC4wZGxibnluLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw   # en Base64


#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode
#kubectl delete -f saori-apaza-01-deployment.yml
#kubectl port-forward service/saori-apaza-01-service -n saori-apaza-01-namespace 8085:8080