apiVersion: v1
kind: Service
metadata:
  name: saori-apaza-01-frontend-service
  namespace: saori-apaza-01-namespace
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: saori-apaza-01-frontend